mysite/account/urls.py
from django.urls import path
from .views import *

app_name = "account"

urlpatterns = [
    path("", Home.as_view(), name="home"),
    path("register/", Register.as_view(), name="register"),
    path("login/", Login.as_view(), name="login"),
    path("log_out/", LogOut.as_view(), name="log_out"),
]

mysite/file/urls.py
from django.urls import path
from .views import *

app_name = "file"

urlpatterns = [
    path("new_directory/", CreateDirectory.as_view(), name="new_directory"),
    path("create_file/", CreateFile.as_view(), name="create_file"),
    path("directory/<int:id>/", DirectoryView.as_view(), name="directory"),

    path("Dmanage/", Delete_item.as_view(), name="delete_manage"),
    path("manage/<str:type>/<int:id>/", Delete_item.as_view(), name="delete_manage"),

    path("Emanage/", Edit_item.as_view(), name="edit_manage"),
    path("manage/<str:type>/<int:id>/", Edit_item.as_view(), name="edit_manage"),

    path("Smanage/", Share_item.as_view(), name="share_manage"), 
    path("manage/<str:type>/<int:id>/", Share_item.as_view(), name="share_manage"),
]

mysite/mysite/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include("account.urls", namespace="account")),
    path('', include("file.urls", namespace="file")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- css icon in this site : https://www.w3schools.com/icons/icons_reference.asp -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body dir="rtl">



    <nav class="navbar navbar-expand-lg navbar-light bg-primary">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <a class="navbar-brand" href="#">منو</a>
          <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <ul class="navbar-nav mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'account:home' %}">خانه</a>
              </li>
              {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account:log_out' %}">خروج</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">مدیریت حافظه</a>
              </li>
              <li class="nav-item">
                <a onclick="open_create_file_function()" class="nav-link" href="#">آپلود فایل</a>
              </li>
              <li class="nav-item">
                <a onclick="open_add_directory_function()" class="nav-link" href="#">ایجاد پوشه</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account:register' %}">ثبت نام</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account:login' %}">ورود</a>
              </li>
              {% endif %}
            </ul>
            <!-- <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form> -->
          </div>
        </div>
      </nav>




        {% block content %}{% endblock %}



    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>



{% block script %}{% endblock %}


  </body>
</html>