mysite/file/urls.py
from django.urls import path
from .views import *

app_name = "file"

urlpatterns = [
    path("new_directory/", CreateDirectory.as_view(), name="new_directory"),
    path("create_file/", CreateFile.as_view(), name="create_file"),
    path("directory/<int:id>/", DirectoryView.as_view(), name="directory"),

    path("Dmanage/", Delete_item.as_view(), name="delete_manage"),
    path("manage/<str:type>/<int:id>/", Delete_item.as_view(), name="delete_manage"),

    path("Emanage/", Edit_item.as_view(), name="edit_manage"),
    path("manage/<str:type>/<int:id>/", Edit_item.as_view(), name="edit_manage"),

    path("Smanage/", Share_item.as_view(), name="share_manage"), 
    path("manage/<str:type>/<int:id>/", Share_item.as_view(), name="share_manage"),
]

mysite/mysite/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include("account.urls", namespace="account")),
    path('', include("file.urls", namespace="file")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/file/models.py
from django.db import models
from django.contrib.auth.models import User

def user_directory_path(instance, filename):
    return f'user_{instance.user.username}/{filename}'

class DirectoryModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=280)
    parent = models.ForeignKey("self", on_delete=models.CASCADE, null=True, blank=True)
    size = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class File(models.Model):
    name = models.CharField(max_length=280, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    directory = models.ForeignKey(DirectoryModel, on_delete=models.CASCADE, null=True, blank=True)
    file = models.FileField(upload_to=user_directory_path)
    size = models.IntegerField()

    def __str__(self):
        return self.name


class PermissionUser(models.Model):
    TYPE = (
        ("d", "directory"), 
        ("f", "file")
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    file = models.ForeignKey(File, on_delete=models.CASCADE, null=True, blank=True)
    directory = models.ForeignKey(DirectoryModel, on_delete=models.CASCADE, null=True, blank=True)
    type = models.CharField(max_length=1, choices=TYPE)

    def __str__(self):
        return self.id

mysite/file/views.py
from msilib.schema import Directory
from unicodedata import category
from django.shortcuts import redirect, render
from django.views import View
from django.contrib import messages
from .models import *


class CreateDirectory(View):
    def post(self, request):
        data = request.POST
        if data["directory_id"] == '0':
            DirectoryModel.objects.create(user=request.user, name=data["name"])
            return redirect("account:home")
        else:
            direcory = DirectoryModel.objects.get(id=str(data["directory_id"]))
            DirectoryModel.objects.create(user=request.user, name=data["name"], parent=direcory)
            return redirect("file:directory", id=direcory.id)



class CreateFile(View):
    def post(self, request):
        data = request.FILES.getlist('file')
        directory_id = request.POST["directory_id"]
        
        if directory_id == '0':
            messages.warning(request, 'خطا ! در صفحه اصلی نمیتوانید فایلی آپلود کنید')
            return redirect("account:home")

        directory = DirectoryModel.objects.get(id=directory_id)
        for file in data:
            with open(f'./file_size/{str(file)}', 'wb+')as f:
                f.write(file.read())
            size = os.path.getsize(f'./file_size/{str(file)}')
            os.remove(f'./file_size/{str(file)}')
            directory.size += size
            directory.save()
            File.objects.create(user=request.user, file=file, name=str(file), directory=directory, size=size)
        return redirect("account:home")



class DirectoryView(View):
    def get(self, request, id):
        if request.user.is_authenticated:
            user = User.objects.get(username=request.user)
            directory = DirectoryModel.objects.filter(user=user).filter(parent=id)
            files = File.objects.filter(user=user).filter(directory=id)
            return render(request, "file/main.html", context={"user": request.user, "directory_id": id, "directory":directory, "files":files})



class Delete_item(View):
    def get(self, request, type, id):
        return render(request, "file/manage.html", context={"type":type, "id":id})
    def post(self, request):
        data = request.POST
        if data["type"] == "delete_directory":
            directory = DirectoryModel.objects.get(id= data["id"])
            directory.delete()
            return redirect("account:home")
        elif data["type"] == "delete_file":
            pass



class Edit_item(View):
    def get(self, request, type, id):
        return render(request, "file/manage.html", context={"type":type, "id":id})
    def post(self, request):
        data = request.POST
        if data["type"] == "edit_directory":
            directory = DirectoryModel.objects.get(id= data["id"])
            directory.name = data["name"]
            directory.save()
            return redirect("account:home")
        elif data["type"] == "edit_file":
            pass


class Share_item(View):
    def get(self, request, type, id):
        return render(request, "file/manage.html", context={"type":type, "id":id})
    def post(self, request):
        data = request.POST
        if data["type"] == "share_directory":
            user = User.objects.get(username=data["username"])
            directory = DirectoryModel.objects.get(id=data["id"])
            PermissionUser.objects.create(user=user, type="d", directory=directory)
            return redirect("account:home")
        elif data["type"] == "share_file":
            pass

mysite/file/templates/file/main.html
{% extends "base.html" %}


{% block content %}


{% if messages %}
<ul class="messages">
  <div class="alert alert-danger" role="alert">
    {% for message in messages %}
    <li style="text-align:center; list-style-type:none;"> {{ message }} </li>
    {% endfor %}
  </div>
</ul>
{% endif %}

{% if messages %}
{% endif %}



<form id="add_directory" style="text-align: center; margin-top: 10%; display: none;" action="{% url 'file:new_directory' %}" method="post">
    {% csrf_token %}
    <label for="name"></label>
    <input type="hidden", name="directory_id" value="{{ directory_id }}">
    <input style="text-align: center; width: 10%;" type="text" name="name" placeholder="name"/><br><br>
    <a onclick="close_add_directory_function()" style="width: 3%;" class="btn btn-danger" href="#"><i class="fa fa-close"></i></a>
    <button style="width: 3%;" type="submit" class="btn btn-success"><i class="fa fa-check"></i></button>
</form>


<form id="create_file" enctype="multipart/form-data" style="text-align: center; margin-top: 10%; display: none;" action="{% url 'file:create_file' %}" method="post">
  {% csrf_token %}
  <input type="hidden", name="directory_id" value="{{ directory_id }}">
  <input type="file" name="file" id="file" multiple style="display:none;"/>
  <label for="file"><span class="btn btn-secondary" style="font-size:24px">UPLOAD<i class="fa fa-upload"></i></span></label><br><br>
  <a onclick="close_create_file_function()" style="width: 3%;" class="btn btn-danger" href="#"><i class="fa fa-close"></i></a>
  <button style="width: 3%;" type="submit" class="btn btn-success"><i class="fa fa-check"></i></button>
</form>


<div id="direcory_list" class="container mt-3">
    <div class="row">
        {% for folder in directory %}
        <div class="col-sm-3">
          {% if folder.size == 0 %}
          <button style="font-size:24px; margin: 1% 3%;"><i onclick="open_settings('{{ folder.id }}')" class="material-icons" style="color: black;">settings</i> <a style="color: black; " href="{% url 'file:directory' folder.id %}">{{ folder.name }}</a> <i class="fa fa-folder-open-o"></i>
          <ul style="display: none; list-style: none;" id="{{ folder.id }}">
            <li class="btn btn-danger" onclick="close_settings('{{ folder.id }}')"><i class="fa fa-close"></i></li><br>
            <a href="{% url 'file:delete_manage' 'delete_directory' folder.id %}"><li class="btn btn-danger" >حذف</li></a><br>
            <a href="{% url 'file:edit_manage' 'edit_directory' folder.id %}"><li class="btn btn-warning">تغییر نام</li></a><br>
            <a href="{% url 'file:share_manage' 'share_directory' folder.id %}"><li class="btn btn-primary">اشتراک گذاری</li></a><br>
          </ul></button>
          {% else %}
          <button style="font-size:24px; margin: 1% 3%;"><i onclick="open_settings('{{ folder.id }}')" class="material-icons" style="color: black;">settings</i> <a style="color: black; " href="{% url 'file:directory' folder.id %}">{{ folder.name }}</a> <i class="fa fa-folder-open"></i>
          <ul style="display: none; list-style: none;" id="{{ folder.id }}">
            <li class="btn btn-danger" onclick="close_settings('{{ folder.id }}')"><i class="fa fa-close"></i></li><br>
            <a href="{% url 'file:delete_manage' 'delete_directory' folder.id %}"><li class="btn btn-danger" >حذف</li></a><br>
            <a href="{% url 'file:edit_manage' 'edit_directory' folder.id %}"><li class="btn btn-warning">تغییر نام</li></a><br>
            <a href="{% url 'file:share_manage' 'share_directory' folder.id %}"><li class="btn btn-primary">اشتراک گذاری</li></a><br>
          </ul></button>
          {% endif %}
        </div>
        {% endfor %}
    </div>
  </div>


{% if directory|length != 0 and files|length != 0 %}
<hr>
{% endif %}



{% if files|length > 0 %}
<table id="files" class="table">
  <thead>
    <tr>
      <th scope="col">name</th>
      <th scope="col"></th>
      <th scope="col">size</th>
    </tr>
  </thead>
  <tbody>
    {% for file in files %}
      <tr>
        <th scope="row"><span style="font-size:10px; margin: 1% 3%;"><a href="{{ file.file.url }}">{{ file.name|truncatechars:100 }}</a></span></th>
        {% if '.jpg' in file.name %}
        <th scope="row"><img style="width: 40px; height: 40px;" src=" {{ file.file.url }} " alt="image"></th>
        {% elif '.mp4' in file.name %}
        <th scope="row"><i class="material-icons" style="font-size:36px">ondemand_video</i></th>
        {% else %}
        <th scope="row"><i class="fa fa-files-o" style="font-size:36px;"></i></th>
        {% endif %}
        <th scope="row"><span style="font-size:10px; margin: 1% 3%;">{{ file.size }}</span></th>
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endif %}



  





{% endblock %}



{% block script %}
<script>
    function open_add_directory_function(){
        document.getElementById("add_directory").style.display = "block";
        document.getElementById("direcory_list").style.display = "none";
        document.getElementById("create_file").style.display = "none";
        document.getElementById("files").style.display = "none";
    }
    function close_add_directory_function(){
      window.location.reload();
        // document.getElementById("add_directory").style.display = "none";
        // document.getElementById("direcory_list").style.display = "block";
        // document.getElementById("files").style.display = "block";
    }

    function open_create_file_function(){
        document.getElementById("create_file").style.display = "block";
        document.getElementById("direcory_list").style.display = "none";
        document.getElementById("add_directory").style.display = "none";
        document.getElementById("files").style.display = "none";
    }
    function close_create_file_function(){
      window.location.reload();
        // document.getElementById("create_file").style.display = "none";
        // document.getElementById("direcory_list").style.display = "block";
        // document.getElementById("files").style.display = "block";
    }

    function open_settings(id){
        console.log(id)
        document.getElementById(id).style.display = "block";
    }
    function close_settings(id){
        console.log(id)
        document.getElementById(id).style.display = "none";
    }
</script>
{% endblock %}

mysite/file/templates/file/manage.html
{% extends 'base.html' %}

{% block content %}

{% if "delete" in type %}
<form id="add_directory" style="text-align: center; margin-top: 10%;" action="{% url 'file:delete_manage' %}" method="post">
    {% csrf_token %}
    <label for="text">آیا از حذف مطمئنید ؟</label>
    <input type="hidden" name="type" value="{{ type }}">
    <input type="hidden" name="id" value="{{ id }}">
    <a style="width: 3%;" class="btn btn-danger" href="/"><i class="fa fa-close"></i></a>
    <button style="width: 3%;" type="submit" class="btn btn-success"><i class="fa fa-check"></i></button>
</form>
{% elif "edit" in type %}
<form id="add_directory" style="text-align: center; margin-top: 10%;" action="{% url 'file:edit_manage' %}" method="post">
    {% csrf_token %}
    <label for="name">name</label><br>
    <input style="text-align: center;" type="text" name="name" placeholder="name"><br><br>
    <input type="hidden" name="type" value="{{ type }}">
    <input type="hidden" name="id" value="{{ id }}">
    <a style="width: 3%;" class="btn btn-danger" href="/"><i class="fa fa-close"></i></a>
    <button style="width: 3%;" type="submit" class="btn btn-success"><i class="fa fa-check"></i></button>
</form>
{% elif "share" in type %}
<form id="add_directory" style="text-align: center; margin-top: 10%;" action="{% url 'file:share_manage' %}" method="post">
    {% csrf_token %}
    <label for="name">username</label><br>
    <input style="text-align: center;" type="text" name="username" placeholder="username"><br><br>
    <input type="hidden" name="type" value="{{ type }}">
    <input type="hidden" name="id" value="{{ id }}">
    <a style="width: 3%;" class="btn btn-danger" href="/"><i class="fa fa-close"></i></a>
    <button style="width: 3%;" type="submit" class="btn btn-success"><i class="fa fa-check"></i></button>
</form>
{% endif %}

{% endblock %}